package com.github.tndavidson.geodespringbootpoc.repository;

import lombok.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.gemfire.repository.query.QueryPostProcessor;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.query.QueryMethod;
import org.springframework.stereotype.Component;

/**
 * A Spring {@link Component} that implements {@link QueryPostProcessor} to intercept and log
 * OQL queries generated by {@link CustomerRepository}.
 * <p>
 * This post-processor is invoked by the Spring Data Geode framework after a query is
 * derived from a repository method but before it is executed against the Geode cache.
 * It provides visibility into the generated OQL strings and the arguments passed to them.
 */
@Component
public class QueryLoggingPostProcessor implements QueryPostProcessor<Repository, String> {
    private static final Logger LOGGER = LoggerFactory.getLogger(QueryLoggingPostProcessor.class);

    @Override
    public String postProcess(@NonNull QueryMethod queryMethod, String query, Object... arguments) {
        LOGGER.debug("Executing query {} with arguments {}", query, arguments);
        return query;
    }
}
