package com.github.tndavidson.geodespringbootpoc.processor;

import org.apache.geode.cache.query.CqEvent;

/**
 * Functional interface for processing new transactions in response to events
 * generated by a continuous query. Implementations of this interface define
 * the logic for handling new transaction events.
 *
 * This interface ensures that the processing logic is focused on handling
 * individual transaction events, which may involve actions such as updating
 * related account balances or triggering downstream processes.
 */
@FunctionalInterface
public interface TransactionPostProcessor {

    /**
     * Processes a new transaction event triggered by a continuous query. This method
     * handles the logic required to process a transaction event, such as updating
     * account balances or performing related operations.
     *
     * @param event the continuous query event that contains the details of the
     *              new transaction to be processed
     */
    void processNewTransaction(CqEvent event);
}
